engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
      config:
        config: .eslintrc.js
      enabled: true
  fixme:
    enabled: true
exclude_paths:
  - "**.spec.js"